CREATE TABLE DiscardMenuItem (
    Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    menuItemId INT NOT NULL,
    avgRating FLOAT NOT NULL,
    FOREIGN KEY (menuItemId) REFERENCES Menu(Id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);