
ALTER TABLE PreparedMenuItem
ADD CONSTRAINT fk_PreparedMenuItem_menuItemId
FOREIGN KEY (menuItemId) REFERENCES Menu(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE RolledOutMenuItem DROP FOREIGN KEY fk_menuItemId;
ALTER TABLE RolledOutMenuItem
ADD CONSTRAINT fk_RolledOutMenuItem_menuItemId
FOREIGN KEY (menuItemId) REFERENCES Menu(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Vote DROP FOREIGN KEY vote_ibfk_1;
ALTER TABLE Vote DROP FOREIGN KEY vote_ibfk_2;

ALTER TABLE Vote
ADD CONSTRAINT fk_Vote_menuItemId
FOREIGN KEY (menuItemId) REFERENCES Menu(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Vote
ADD CONSTRAINT fk_Vote_userId
FOREIGN KEY (userId) REFERENCES User(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Feedback DROP FOREIGN KEY feedback_ibfk_1;
ALTER TABLE Feedback
ADD CONSTRAINT fk_Feedback_menuItemId
FOREIGN KEY (menuItemId) REFERENCES Menu(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Feedback DROP FOREIGN KEY feedback_ibfk_2;
ALTER TABLE Feedback
ADD CONSTRAINT fk_Feedback_userId
FOREIGN KEY (userId) REFERENCES User(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Notification DROP FOREIGN KEY notification_ibfk_1;
ALTER TABLE Notification
ADD CONSTRAINT fk_Notification_notificationTypeId
FOREIGN KEY (notificationTypeId) REFERENCES NotificationType(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Notification DROP FOREIGN KEY notification_ibfk_2;
ALTER TABLE Notification
ADD CONSTRAINT fk_Notification_userId
FOREIGN KEY (userId) REFERENCES User(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Menu DROP FOREIGN KEY fk_mealType;
ALTER TABLE Menu
ADD CONSTRAINT fk_Menu_mealTypeId
FOREIGN KEY (mealTypeId) REFERENCES MealType(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE User DROP FOREIGN KEY user_ibfk_1;
ALTER TABLE User
ADD CONSTRAINT fk_User_userRoleId
FOREIGN KEY (userRoleId) REFERENCES UserRole(Id)
ON DELETE CASCADE
ON UPDATE CASCADE;