DROP TABLE IF EXISTS User;

CREATE TABLE User (
    Id INT PRIMARY KEY NOT NULL,
    userRoleID INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    FOREIGN KEY (userRoleId) REFERENCES UserRole(Id)
);