CREATE TABLE DetailedFeedback (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    menuItemId INT NOT NULL,
    dateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (menuItemId) REFERENCES MenuItem(id) ON DELETE CASCADE ON UPDATE CASCADE
);